from setuptools import setup


setup(
    name='bounded-iterator',
    version='0.1.1',
    description='Limits the number of values generated by an iterator until acknowledged.',
    long_description=open('README.rst', 'rt', encoding='utf-8').read(),
    url='https://github.com/jruere/bounded-iterator',
    license="LGPLv3",
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    keywords="concurrency parallelism iterator iterable multiprocessing imap",
    author="Javier Ruere",
    author_email="javier@ruere.com.ar",
    zip_safe=True,
    py_modules=['bounded_iterator'],
    platforms=["POSIX"],
    test_suite="test_bounded_iterator.py",
    install_requires=[],
    tests_require=[],
)
